# Generated by Django 4.2.6 on 2023-10-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_rename_newsletter_log_mailings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='mailings',
            new_name='mailing',
        ),
    ]
