# Generated by Django 4.2.6 on 2023-10-31 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_alter_mailings_options_alter_log_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-id',), 'verbose_name': 'Письмо', 'verbose_name_plural': 'Письма'},
        ),
    ]
