# Generated by Django 4.2.6 on 2023-10-31 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-id',), 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
    ]
